// <auto-generated />
namespace Trendy.Migrations

open System
open Microsoft.EntityFrameworkCore
open Microsoft.EntityFrameworkCore.Infrastructure
open Microsoft.EntityFrameworkCore.Metadata
open Microsoft.EntityFrameworkCore.Migrations
open Microsoft.EntityFrameworkCore.Storage.ValueConversion
open Trendy.Contexts

[<DbContext(typeof<LinksContext.LinksContext>)>]
[<Migration("20210703031809_ReplaceUserWithUserIdInLink")>]
type ReplaceUserWithUserIdInLink() =
    inherit Migration()

    override this.Up(migrationBuilder:MigrationBuilder) =
        ()

    override this.Down(migrationBuilder:MigrationBuilder) =
        ()

    override this.BuildTargetModel(modelBuilder: ModelBuilder) =
        modelBuilder
            .HasAnnotation("ProductVersion", "5.0.7")
            |> ignore

        modelBuilder.Entity("Trendy.Models.DatabaseTypes+Link", (fun b ->

            b.Property<int>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("INTEGER") |> ignore
            b.Property<string>("Notes")
                .HasColumnType("TEXT") |> ignore
            b.Property<string>("Url")
                .IsRequired()
                .HasColumnType("TEXT") |> ignore
            b.Property<int>("UserId")
                .IsRequired()
                .HasColumnType("INTEGER") |> ignore

            b.HasKey("Id") |> ignore


            b.HasIndex("UserId") |> ignore

            b.ToTable("Links") |> ignore

        )) |> ignore

        modelBuilder.Entity("Trendy.Models.DatabaseTypes+User", (fun b ->

            b.Property<int>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("INTEGER") |> ignore
            b.Property<string>("Email")
                .IsRequired()
                .HasColumnType("TEXT") |> ignore
            b.Property<string>("EncryptedPassword")
                .IsRequired()
                .HasColumnType("TEXT") |> ignore
            b.Property<string>("Name")
                .IsRequired()
                .HasColumnType("TEXT") |> ignore

            b.HasKey("Id") |> ignore


            b.HasIndex("Email")
                .IsUnique() |> ignore

            b.ToTable("Users") |> ignore

        )) |> ignore

        modelBuilder.Entity("Trendy.Models.DatabaseTypes+Link", (fun b ->
            b.HasOne("Trendy.Models.DatabaseTypes+User",null)
                .WithMany("Links")
                .HasForeignKey("UserId")
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired() |> ignore
        )) |> ignore

