// <auto-generated />
namespace Trendy.Migrations

open System
open Microsoft.EntityFrameworkCore
open Microsoft.EntityFrameworkCore.Infrastructure
open Microsoft.EntityFrameworkCore.Metadata
open Microsoft.EntityFrameworkCore.Migrations
open Microsoft.EntityFrameworkCore.Storage.ValueConversion
open Trendy.Contexts

[<DbContext(typeof<LinksContext.LinksContext>)>]
[<Migration("20210619151621_AddUser")>]
type AddUser() =
    inherit Migration()

    override this.Up(migrationBuilder:MigrationBuilder) =
        migrationBuilder.CreateTable(
            name = "Users"
            ,columns = (fun table -> 
            {|
                Id =
                    table.Column<int>(
                        nullable = false
                        ,``type`` = "INTEGER"
                    ).Annotation("Sqlite:Autoincrement", true)
                UserName =
                    table.Column<string>(
                        nullable = true
                        ,``type`` = "TEXT"
                    )
                NormalizedUserName =
                    table.Column<string>(
                        nullable = true
                        ,``type`` = "TEXT"
                    )
                Email =
                    table.Column<string>(
                        nullable = true
                        ,``type`` = "TEXT"
                    )
                NormalizedEmail =
                    table.Column<string>(
                        nullable = true
                        ,``type`` = "TEXT"
                    )
                EmailConfirmed =
                    table.Column<bool>(
                        nullable = false
                        ,``type`` = "INTEGER"
                    )
                PasswordHash =
                    table.Column<string>(
                        nullable = true
                        ,``type`` = "TEXT"
                    )
                SecurityStamp =
                    table.Column<string>(
                        nullable = true
                        ,``type`` = "TEXT"
                    )
                ConcurrencyStamp =
                    table.Column<string>(
                        nullable = true
                        ,``type`` = "TEXT"
                    )
                PhoneNumber =
                    table.Column<string>(
                        nullable = true
                        ,``type`` = "TEXT"
                    )
                PhoneNumberConfirmed =
                    table.Column<bool>(
                        nullable = false
                        ,``type`` = "INTEGER"
                    )
                TwoFactorEnabled =
                    table.Column<bool>(
                        nullable = false
                        ,``type`` = "INTEGER"
                    )
                LockoutEnd =
                    table.Column<DateTimeOffset>(
                        nullable = true
                        ,``type`` = "TEXT"
                    )
                LockoutEnabled =
                    table.Column<bool>(
                        nullable = false
                        ,``type`` = "INTEGER"
                    )
                AccessFailedCount =
                    table.Column<int>(
                        nullable = false
                        ,``type`` = "INTEGER"
                    )
            |})
            ,constraints =
                (fun table -> 
                    table.PrimaryKey("PK_Users", (fun x -> (x.Id) :> obj)) |> ignore
                ) 
        ) |> ignore


    override this.Down(migrationBuilder:MigrationBuilder) =
        migrationBuilder.DropTable(
            name = "Users"
            ) |> ignore


    override this.BuildTargetModel(modelBuilder: ModelBuilder) =
        modelBuilder
            .HasAnnotation("ProductVersion", "5.0.7")
            |> ignore

        modelBuilder.Entity("Trendy.Models.Link+Link", (fun b ->

            b.Property<int>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("INTEGER") |> ignore
            b.Property<string>("Notes")
                .HasColumnType("TEXT") |> ignore
            b.Property<string>("Url")
                .HasColumnType("TEXT") |> ignore

            b.HasKey("Id") |> ignore

            b.ToTable("Links") |> ignore

        )) |> ignore

        modelBuilder.Entity("Trendy.Models.User+User", (fun b ->

            b.Property<int>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("INTEGER") |> ignore
            b.Property<int>("AccessFailedCount")
                .IsRequired()
                .HasColumnType("INTEGER") |> ignore
            b.Property<string>("ConcurrencyStamp")
                .HasColumnType("TEXT") |> ignore
            b.Property<string>("Email")
                .HasColumnType("TEXT") |> ignore
            b.Property<bool>("EmailConfirmed")
                .IsRequired()
                .HasColumnType("INTEGER") |> ignore
            b.Property<bool>("LockoutEnabled")
                .IsRequired()
                .HasColumnType("INTEGER") |> ignore
            b.Property<Nullable<DateTimeOffset>>("LockoutEnd")
                .HasColumnType("TEXT") |> ignore
            b.Property<string>("NormalizedEmail")
                .HasColumnType("TEXT") |> ignore
            b.Property<string>("NormalizedUserName")
                .HasColumnType("TEXT") |> ignore
            b.Property<string>("PasswordHash")
                .HasColumnType("TEXT") |> ignore
            b.Property<string>("PhoneNumber")
                .HasColumnType("TEXT") |> ignore
            b.Property<bool>("PhoneNumberConfirmed")
                .IsRequired()
                .HasColumnType("INTEGER") |> ignore
            b.Property<string>("SecurityStamp")
                .HasColumnType("TEXT") |> ignore
            b.Property<bool>("TwoFactorEnabled")
                .IsRequired()
                .HasColumnType("INTEGER") |> ignore
            b.Property<string>("UserName")
                .HasColumnType("TEXT") |> ignore

            b.HasKey("Id") |> ignore

            b.ToTable("Users") |> ignore

        )) |> ignore

